/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IUiPoolDataProviderInterface extends ethers.utils.Interface {
  functions: {
    "getReservesData(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getReservesData",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getReservesData",
    data: BytesLike
  ): Result;

  events: {};
}

export class IUiPoolDataProvider extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IUiPoolDataProviderInterface;

  functions: {
    getReservesData(
      provider: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          boolean,
          boolean,
          boolean,
          boolean,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          number,
          string,
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          underlyingAsset: string;
          name: string;
          symbol: string;
          decimals: BigNumber;
          baseLTVasCollateral: BigNumber;
          reserveLiquidationThreshold: BigNumber;
          reserveLiquidationBonus: BigNumber;
          reserveFactor: BigNumber;
          usageAsCollateralEnabled: boolean;
          borrowingEnabled: boolean;
          stableBorrowRateEnabled: boolean;
          isActive: boolean;
          isFrozen: boolean;
          liquidityIndex: BigNumber;
          variableBorrowIndex: BigNumber;
          liquidityRate: BigNumber;
          variableBorrowRate: BigNumber;
          stableBorrowRate: BigNumber;
          lastUpdateTimestamp: number;
          aTokenAddress: string;
          stableDebtTokenAddress: string;
          variableDebtTokenAddress: string;
          interestRateStrategyAddress: string;
          availableLiquidity: BigNumber;
          totalPrincipalStableDebt: BigNumber;
          averageStableRate: BigNumber;
          stableDebtLastUpdateTimestamp: BigNumber;
          totalScaledVariableDebt: BigNumber;
          priceInEth: BigNumber;
          variableRateSlope1: BigNumber;
          variableRateSlope2: BigNumber;
          stableRateSlope1: BigNumber;
          stableRateSlope2: BigNumber;
        })[],
        ([
          string,
          BigNumber,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          underlyingAsset: string;
          scaledATokenBalance: BigNumber;
          usageAsCollateralEnabledOnUser: boolean;
          stableBorrowRate: BigNumber;
          scaledVariableDebt: BigNumber;
          principalStableDebt: BigNumber;
          stableBorrowLastUpdateTimestamp: BigNumber;
        })[],
        BigNumber
      ]
    >;

    "getReservesData(address,address)"(
      provider: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          boolean,
          boolean,
          boolean,
          boolean,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          number,
          string,
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          underlyingAsset: string;
          name: string;
          symbol: string;
          decimals: BigNumber;
          baseLTVasCollateral: BigNumber;
          reserveLiquidationThreshold: BigNumber;
          reserveLiquidationBonus: BigNumber;
          reserveFactor: BigNumber;
          usageAsCollateralEnabled: boolean;
          borrowingEnabled: boolean;
          stableBorrowRateEnabled: boolean;
          isActive: boolean;
          isFrozen: boolean;
          liquidityIndex: BigNumber;
          variableBorrowIndex: BigNumber;
          liquidityRate: BigNumber;
          variableBorrowRate: BigNumber;
          stableBorrowRate: BigNumber;
          lastUpdateTimestamp: number;
          aTokenAddress: string;
          stableDebtTokenAddress: string;
          variableDebtTokenAddress: string;
          interestRateStrategyAddress: string;
          availableLiquidity: BigNumber;
          totalPrincipalStableDebt: BigNumber;
          averageStableRate: BigNumber;
          stableDebtLastUpdateTimestamp: BigNumber;
          totalScaledVariableDebt: BigNumber;
          priceInEth: BigNumber;
          variableRateSlope1: BigNumber;
          variableRateSlope2: BigNumber;
          stableRateSlope1: BigNumber;
          stableRateSlope2: BigNumber;
        })[],
        ([
          string,
          BigNumber,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          underlyingAsset: string;
          scaledATokenBalance: BigNumber;
          usageAsCollateralEnabledOnUser: boolean;
          stableBorrowRate: BigNumber;
          scaledVariableDebt: BigNumber;
          principalStableDebt: BigNumber;
          stableBorrowLastUpdateTimestamp: BigNumber;
        })[],
        BigNumber
      ]
    >;
  };

  getReservesData(
    provider: string,
    user: string,
    overrides?: CallOverrides
  ): Promise<
    [
      ([
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        number,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        underlyingAsset: string;
        name: string;
        symbol: string;
        decimals: BigNumber;
        baseLTVasCollateral: BigNumber;
        reserveLiquidationThreshold: BigNumber;
        reserveLiquidationBonus: BigNumber;
        reserveFactor: BigNumber;
        usageAsCollateralEnabled: boolean;
        borrowingEnabled: boolean;
        stableBorrowRateEnabled: boolean;
        isActive: boolean;
        isFrozen: boolean;
        liquidityIndex: BigNumber;
        variableBorrowIndex: BigNumber;
        liquidityRate: BigNumber;
        variableBorrowRate: BigNumber;
        stableBorrowRate: BigNumber;
        lastUpdateTimestamp: number;
        aTokenAddress: string;
        stableDebtTokenAddress: string;
        variableDebtTokenAddress: string;
        interestRateStrategyAddress: string;
        availableLiquidity: BigNumber;
        totalPrincipalStableDebt: BigNumber;
        averageStableRate: BigNumber;
        stableDebtLastUpdateTimestamp: BigNumber;
        totalScaledVariableDebt: BigNumber;
        priceInEth: BigNumber;
        variableRateSlope1: BigNumber;
        variableRateSlope2: BigNumber;
        stableRateSlope1: BigNumber;
        stableRateSlope2: BigNumber;
      })[],
      ([
        string,
        BigNumber,
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        underlyingAsset: string;
        scaledATokenBalance: BigNumber;
        usageAsCollateralEnabledOnUser: boolean;
        stableBorrowRate: BigNumber;
        scaledVariableDebt: BigNumber;
        principalStableDebt: BigNumber;
        stableBorrowLastUpdateTimestamp: BigNumber;
      })[],
      BigNumber
    ]
  >;

  "getReservesData(address,address)"(
    provider: string,
    user: string,
    overrides?: CallOverrides
  ): Promise<
    [
      ([
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        number,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        underlyingAsset: string;
        name: string;
        symbol: string;
        decimals: BigNumber;
        baseLTVasCollateral: BigNumber;
        reserveLiquidationThreshold: BigNumber;
        reserveLiquidationBonus: BigNumber;
        reserveFactor: BigNumber;
        usageAsCollateralEnabled: boolean;
        borrowingEnabled: boolean;
        stableBorrowRateEnabled: boolean;
        isActive: boolean;
        isFrozen: boolean;
        liquidityIndex: BigNumber;
        variableBorrowIndex: BigNumber;
        liquidityRate: BigNumber;
        variableBorrowRate: BigNumber;
        stableBorrowRate: BigNumber;
        lastUpdateTimestamp: number;
        aTokenAddress: string;
        stableDebtTokenAddress: string;
        variableDebtTokenAddress: string;
        interestRateStrategyAddress: string;
        availableLiquidity: BigNumber;
        totalPrincipalStableDebt: BigNumber;
        averageStableRate: BigNumber;
        stableDebtLastUpdateTimestamp: BigNumber;
        totalScaledVariableDebt: BigNumber;
        priceInEth: BigNumber;
        variableRateSlope1: BigNumber;
        variableRateSlope2: BigNumber;
        stableRateSlope1: BigNumber;
        stableRateSlope2: BigNumber;
      })[],
      ([
        string,
        BigNumber,
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        underlyingAsset: string;
        scaledATokenBalance: BigNumber;
        usageAsCollateralEnabledOnUser: boolean;
        stableBorrowRate: BigNumber;
        scaledVariableDebt: BigNumber;
        principalStableDebt: BigNumber;
        stableBorrowLastUpdateTimestamp: BigNumber;
      })[],
      BigNumber
    ]
  >;

  callStatic: {
    getReservesData(
      provider: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          boolean,
          boolean,
          boolean,
          boolean,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          number,
          string,
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          underlyingAsset: string;
          name: string;
          symbol: string;
          decimals: BigNumber;
          baseLTVasCollateral: BigNumber;
          reserveLiquidationThreshold: BigNumber;
          reserveLiquidationBonus: BigNumber;
          reserveFactor: BigNumber;
          usageAsCollateralEnabled: boolean;
          borrowingEnabled: boolean;
          stableBorrowRateEnabled: boolean;
          isActive: boolean;
          isFrozen: boolean;
          liquidityIndex: BigNumber;
          variableBorrowIndex: BigNumber;
          liquidityRate: BigNumber;
          variableBorrowRate: BigNumber;
          stableBorrowRate: BigNumber;
          lastUpdateTimestamp: number;
          aTokenAddress: string;
          stableDebtTokenAddress: string;
          variableDebtTokenAddress: string;
          interestRateStrategyAddress: string;
          availableLiquidity: BigNumber;
          totalPrincipalStableDebt: BigNumber;
          averageStableRate: BigNumber;
          stableDebtLastUpdateTimestamp: BigNumber;
          totalScaledVariableDebt: BigNumber;
          priceInEth: BigNumber;
          variableRateSlope1: BigNumber;
          variableRateSlope2: BigNumber;
          stableRateSlope1: BigNumber;
          stableRateSlope2: BigNumber;
        })[],
        ([
          string,
          BigNumber,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          underlyingAsset: string;
          scaledATokenBalance: BigNumber;
          usageAsCollateralEnabledOnUser: boolean;
          stableBorrowRate: BigNumber;
          scaledVariableDebt: BigNumber;
          principalStableDebt: BigNumber;
          stableBorrowLastUpdateTimestamp: BigNumber;
        })[],
        BigNumber
      ]
    >;

    "getReservesData(address,address)"(
      provider: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          boolean,
          boolean,
          boolean,
          boolean,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          number,
          string,
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          underlyingAsset: string;
          name: string;
          symbol: string;
          decimals: BigNumber;
          baseLTVasCollateral: BigNumber;
          reserveLiquidationThreshold: BigNumber;
          reserveLiquidationBonus: BigNumber;
          reserveFactor: BigNumber;
          usageAsCollateralEnabled: boolean;
          borrowingEnabled: boolean;
          stableBorrowRateEnabled: boolean;
          isActive: boolean;
          isFrozen: boolean;
          liquidityIndex: BigNumber;
          variableBorrowIndex: BigNumber;
          liquidityRate: BigNumber;
          variableBorrowRate: BigNumber;
          stableBorrowRate: BigNumber;
          lastUpdateTimestamp: number;
          aTokenAddress: string;
          stableDebtTokenAddress: string;
          variableDebtTokenAddress: string;
          interestRateStrategyAddress: string;
          availableLiquidity: BigNumber;
          totalPrincipalStableDebt: BigNumber;
          averageStableRate: BigNumber;
          stableDebtLastUpdateTimestamp: BigNumber;
          totalScaledVariableDebt: BigNumber;
          priceInEth: BigNumber;
          variableRateSlope1: BigNumber;
          variableRateSlope2: BigNumber;
          stableRateSlope1: BigNumber;
          stableRateSlope2: BigNumber;
        })[],
        ([
          string,
          BigNumber,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          underlyingAsset: string;
          scaledATokenBalance: BigNumber;
          usageAsCollateralEnabledOnUser: boolean;
          stableBorrowRate: BigNumber;
          scaledVariableDebt: BigNumber;
          principalStableDebt: BigNumber;
          stableBorrowLastUpdateTimestamp: BigNumber;
        })[],
        BigNumber
      ]
    >;
  };

  filters: {};

  estimateGas: {
    getReservesData(
      provider: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getReservesData(address,address)"(
      provider: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getReservesData(
      provider: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getReservesData(address,address)"(
      provider: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
